export const ERROR_STATUS_CODES = {
  // 4xx client error – the request contains bad syntax or cannot be fulfilled
  'Bad Request': 400,
  Unauthorized: 401,
  'Payment Required': 402,
  Forbidden: 403,
  'Not Found': 404,
  'Method Not Allowed': 405,
  'Not Acceptable': 406,
  'Proxy Authentication Required': 407,
  'Request Timeout': 408,
  Conflict: 409,
  Gone: 410,
  'Length Required': 411,
  'Precondition Failed': 412,
  'Payload Too Large': 413,
  'URI Too Long': 414,
  'Unsupported Media Type': 415,
  'Range Not Satisfiable': 416,
  'Expectation Failed': 417,
  'Page Expired': 419,
  'Method Failure': 420,
  'Misdirected Request': 421,
  'Unprocessable Entity': 422,
  Locked: 423,
  'Failed Dependency': 424,
  'Too Early': 425,
  'Upgrade Required': 426,
  'Precondition Required': 428,
  'Too Many Requests': 429,
  'Request Header Fields Too Large': 431,
  'Login Time-out': 440,
  'No Response': 444,
  'Blocked by Windows Parental Controls': 450,
  'Unavailable For Legal Reasons': 451,
  'Request header too large': 494,
  'SSL Certificate Error': 495,
  'SSL Certificate Required': 496,
  'HTTP Request Sent to HTTPS Port': 497,
  'Invalid Token': 498,
  'Token Required': 499,

  // 5xx server error – the server failed to fulfil an apparently valid request
  'Internal Server Error': 500,
  'Not Implemented': 501,
  'Bad Gateway': 502,
  'Service Unavailable': 503,
  'Gateway Timeout': 504,
  'HTTP Version Not Supported': 505,
  'Variant Also Negotiates': 506,
  'Insufficient Storage': 507,
  'Loop Detected': 508,
  'Bandwidth Limit Exceeded': 509,
  'Not Extended': 510,
  'Network Authentication Required': 511,
  'Web Server Returned an Unknown Error': 520,
  'Web Server Is Down': 521,
  'Connection Timed Out': 522,
  'Origin Is Unreachable': 523,
  'SSL Handshake Failed': 525,
  'Invalid SSL Certificate': 526,
  'Site is overloaded': 529,
  'Site is frozen': 530,
  'Network read timeout error': 598,
  'Network Connect Timeout Error': 599,
} as const;

export const STATUS_CODES = {
  // 1xx informational response – the request was received, continuing process
  Continue: 100,
  'Switching Protocols': 101,
  Processing: 102,
  'Early Hints': 103,

  // 2xx successful – the request was successfully received, understood, and accepted
  OK: 200,
  Created: 201,
  Accepted: 202,
  'Non-Authoritative Information': 203,
  'No Content': 204,
  'Reset Content': 205,
  'Partial Content': 206,
  'Multi-Status': 207,
  'Already Reported': 208,
  'IM Used': 226,

  // 3xx redirection – further action needs to be taken in order to complete the request
  'Multiple Choices': 300,
  'Moved Permanently': 301,
  Found: 302,
  'See Other': 303,
  'Not Modified': 304,
  'Use Proxy': 305,
  'Switch Proxy': 306,
  'Temporary Redirect': 307,
  'Permanent Redirect': 308,

  ...ERROR_STATUS_CODES,
} as const;
